name: otbclient
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  flutter_spinkit: ^5.1.0
  flutter_bloc: ^7.3.1
  url_launcher: ^6.0.12
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_cupertino_date_picker_fork: ^1.0.6
  equatable: ^2.0.3
  flutter_easyloading: ^3.0.3
  uuid: ^3.0.5
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  firebase_messaging: ^10.0.9
  firebase_analytics: ^8.3.4
  just_audio: ^0.9.15
  hydrated_bloc: ^7.1.0
  path_provider: ^2.0.6
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0

dependency_overrides:
  test_api: ^0.4.2

flutter_icons:
  image_path_ios: "assets/images/logo_filled.png"
  image_path_android: "assets/images/logo.png"
  remove_alpha_ios: true
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#E4F2EB"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/files/

  #   - images/a_dot_ham.jpeg

  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
